services:
  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qg
    ports:
      - "9092:9092"

  products:
    image: jva44ka/ozon-simulator-go-products:latest
    container_name: products
    ports:
      - "5001:5000"
    environment:
      CONFIG_PATH: /app/configs/products.yaml
    volumes:
      - ./configs/products.yaml:/app/configs/products.yaml:ro
    depends_on:
      - products-db
      - kafka

  cart:
    image: jva44ka/ozon-simulator-go-cart:latest
    container_name: cart
    ports:
      - "5002:5000"
    environment:
      CONFIG_PATH: /app/configs/cart.yaml
    volumes:
      - ./configs/cart.yaml:/app/configs/cart.yaml:ro
    depends_on:
      - cart-db
      - kafka

  products-db:
    image: postgres:17.7
    container_name: products-db
    environment:
      POSTGRES_DB: ozon-simulator-go-products
      POSTGRES_USER: products
      POSTGRES_PASSWORD: products
    ports:
      - "5433:5432"
    volumes:
      - products-db-data:/var/lib/postgresql/data

  products-migrations:
    image: jva44ka/ozon-simulator-go-products:migrator
    container_name: products-migrations
    depends_on:
      - products-db
    command: "postgres://products:products@products-db:5432/ozon-simulator-go-products?sslmode=disable up"

  cart-db:
    image: postgres:17.7
    container_name: cart-db
    environment:
      POSTGRES_DB: ozon-simulator-go-cart
      POSTGRES_USER: cart
      POSTGRES_PASSWORD: cart
    ports:
      - "5434:5432"
    volumes:
      - cart-db-data:/var/lib/postgresql/data

  cart-migrations:
    image: jva44ka/ozon-simulator-go-cart:migrator
    container_name: cart-migrations
    depends_on:
      - cart-db
    command: "postgres://cart:cart@cart-db:5432/ozon-simulator-go-cart?sslmode=disable up"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - products
      - cart

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./configs/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

volumes:
  products-db-data:
  cart-db-data:
  grafana-data:
