version: "3.7"

services:
  reviews:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - products

  products:
    image: gitlab-registry.ozon.dev/go/classroom-16/students/homework-draft/products:latest
    ports:
      - "8082:8082"