server:
  host:
  port: 5000

product:
  schema: http
  host: product
  port: 8002
  auth-token: admin
  timeout: 30s

database:
  user: cart
  password: cart
  host: cart-db
  port: 5432
  name: marketplace-simulator-cart

tracing:
  enabled: true
  otlp-endpoint: tempo:4317

jobs:
  reservation-confirmation-outbox:
    enabled: true
    job-interval: 10ms
    batch-size: 100
    max-retries: 5
  reservation-confirmation-outbox-monitor:
    enabled: true
    job-interval: 10s