server:
  host:
  port: 5000

products:
  schema: http
  host: products
  port: 8002
  auth-token: admin
  timeout: 30s

database:
  user: cart
  password: cart
  host: cart-db
  port: 5432
  name: ozon-simulator-go-cart

kafka:
  brokers:
    - kafka:9092
  reservation-expired-topic: reservation-expired
  consumer-group: cart-reservation-consumer
