product-client:
  host: product
  port: 5000
  auth-token: admin
  timeout: 30s

cart-client:
  host: cart
  port: 5000
  timeout: 30s

kafka:
  brokers:
    - kafka:9092
  product-events-topic: product.events
  consumer-group: loadgen

skus: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

workers:
  replenisher:
    enabled: true
    parallelism: 3
    low-stock-threshold: 10
    replenish-count: 50

  order-flow:
    enabled: true
    parallelism: 50
    rps: 200

  cart-viewer:
    enabled: true
    parallelism: 10
    rps: 500
