http-server:
  host:
  port: 5000

grpc-server:
  host: localhost
  port: 8002

database:
  user: products
  password: products
  host: products-db
  port: 5432
  name: ozon-simulator-go-products

authorization:
  enabled: true
  admin-user: admin

logging:
  log-request-body: true
  log-response-body: true

kafka:
  brokers:
    - kafka:9092
  product-events-topic: product.events

jobs:
  reservation-expiry:
    enabled: true
    ttl: 24h
    job-interval: 10m
  product-events-outbox:
    enabled: true
    job-interval: 1s
    batch-size: 100
    max-retries: 5
