http-server:
  host:
  port: 5000

grpc-server:
  host: localhost
  port: 8002

database:
  user: product
  password: product
  host: product-db
  port: 5432
  name: marketplace-simulator-product

authorization:
  enabled: true
  admin-user: admin

logging:
  log-request-body: true
  log-response-body: true

kafka:
  brokers:
    - kafka:9092
  product-events-topic: product.events
  write-timeout: 5s

rate-limiter:
  enabled: true
  rps: 500
  burst: 50

tracing:
  enabled: true
  otlp-endpoint: tempo:4317

jobs:
  reservation-expiry:
    enabled: true
    ttl: 5m
    job-interval: 1s
  product-events-outbox:
    enabled: true
    job-interval: 10ms
    batch-size: 100
    max-retries: 5
  product-events-outbox-monitor:
    enabled: true
    job-interval: 10s