@startuml

actor User as u
collections LOMS as l
database OrdersStorage as os
database StocksStorage as ss

u -> l : gRPC Loms.OrderPay\n\t- orderID
activate l
l -> os : order.GetByID()
l -> ss : stocks.ReserveRemove()
l -> os : order.SetStatus(payed)

l -> u : Response: OK (code_id=0)

deactivate l

@enduml
